# Enable true color support in screen or tmux
set -ga terminal-overrides ",screen-256color*:Tc"

# Set default terminal type to screen with 256 colors
set-option -g default-terminal "screen-256color"

# Set escape time to 0 milliseconds for faster key response
set -s escape-time 0

unbind r
bind r source-file ~/.tmux.conf

# Set prefix, the leader key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Set mouse on
set -g mouse on

# Pane navigation to vim motions
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Status bar at top
set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "arcticicestudio/nord-tmux"

#set -g @nord_tmux_no_patched_font "1"

# Initializ TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
